---
title: "Related Events"
format: html
---

## 2024

- [Virtual Creatures Competition (VCC)!](https://sites.google.com/view/vcc-2024)
- Engineering the open-ended evolution of synthetic biology
- [Automatic Design of Robot Bodies and Brains with Evolutionary Algorithms](https://www.mn.uio.no/ifi/english/research/groups/robin/events/Tutorials/Tutorial-ALIFE2024/Tutorial-ALIFE2024)
- JAX for Scaling Up Artificial Life
- Neuroevolution
- SwissGL/GPU: tiny libraries for tiny and beautiful programs on the web

## 2023

- OpenMOLE (model exploration and validation)
- [Phylogenies (how and why to track them)](https://emilydolson.github.io/alife-phylogeny-tutorial/)
- [Evolving Robot Bodies and Brains in Unity](https://www.mn.uio.no/ifi/english/research/groups/robin/events/Tutorials/Tutorial%20-%20Artificial%20Life%20-%202023/Artificial%20Life%202023%20-%20Evolving%20Robot%20Bodies%20and%20Brains.html)
- Cellular Automata
- [Self-Organizing Systems with Machine Learning](https://selforgml.github.io/)

## 2022

- Introduction to Using Symbulation
- Simulating pandemics with agent-based models

## 2021

- Behavioral and Cognitive Robotics, an adaptive perspective

## 2020

- The Bibites: Getting the online community involved into Alife through game development (Bibites)
- Introduction to MABE, A tool for studying evolving systems and digital brains (MABE)
- Large Scale Agent Based Modelling with FLAME GPU 2 (FLAME GPU 2)
- Molecular programming of swarms for ALife (MolProg)
- Programming soft alife with SPLAT and ulam (HackSPLAT)
- Visualization Principles and Techniques for Research in ALife (ALifeVis2020)

## 2019

- Intelligent Systems for Smart Cities
- Introduction to Avida-ED

## 2018

- Avida-ED
- Create predictions with neural networks
